# Generated by Django 6.0.2 on 2026-03-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('documents', 'IDs & Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=20)),
                ('location_found', models.CharField(choices=[('library', 'Main Library'), ('cafeteria', 'Cafeteria'), ('gym', 'Gymnasium'), ('parking', 'Parking Lot A'), ('lobby', 'Main Lobby'), ('other', 'Other')], max_length=20)),
                ('date_found', models.DateField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('damaged', 'Damaged')], max_length=20)),
                ('is_valuable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='found_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'found_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
