# Generated by Django 6.0.2 on 2026-03-15 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('documents', 'Documents'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair (Scratched)'), ('poor', 'Damaged')], max_length=20)),
                ('location_lost', models.CharField(choices=[('library', 'Main Library'), ('cafeteria', 'Student Cafeteria'), ('gym', 'Sports Gym'), ('hall_a', 'Lecture Hall A'), ('dorm', 'Dormitory Block'), ('other', 'Other')], max_length=20)),
                ('date_lost', models.DateField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='lost_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('searched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
