# Generated by Django 6.0.2 on 2026-03-22 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lostitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claim_status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='claim_status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='FoundItemClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_item_claims', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.founditem')),
            ],
            options={
                'db_table': 'found_item_claims',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('found_item', 'claimed_by'), name='unique_found_item_claim_per_user')],
            },
        ),
    ]
