# Generated by Django 6.0.2 on 2026-03-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_founditem_claim_status_lostitem_claim_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('proof_image', models.FileField(blank=True, null=True, upload_to='claim_verifications/')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('admin_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.founditemclaim')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_verifications', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.founditem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claim_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_verification',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
