# Generated by Django 6.0.2 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_claimverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimverification',
            name='status',
            field=models.CharField(
                choices=[
                    ('unverified', 'Unverified'),
                    ('verified', 'Verified'),
                    ('rejected', 'Rejected'),
                    ('closed', 'Closed'),
                ],
                default='unverified',
                max_length=20,
            ),
        ),
    ]
