# Generated by Django 6.0.2 on 2026-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_claimverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='location_found',
            field=models.CharField(choices=[('cafeteria', 'Cafeteria'), ('classroom', 'Classroom'), ('lecture_hall', 'Lecture Hall'), ('parking', 'Parking Lot A'), ('library', 'Library'), ('playground', 'Playground')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('damaged', 'Damaged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location_lost',
            field=models.CharField(choices=[('cafeteria', 'Cafeteria'), ('classroom', 'Classroom'), ('lecture_hall', 'Lecture Hall'), ('parking', 'Parking Lot A'), ('library', 'Library'), ('playground', 'Playground')], max_length=20),
        ),
    ]
