# Generated by Django 6.0.2 on 2026-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_founditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('stationery', 'Stationery'), ('jewellery', 'Jewellery'), ('bottle', 'Bottle'), ('wallet', 'Wallet'), ('bags', 'Bags'), ('documents', 'Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('stationery', 'Stationery'), ('jewellery', 'Jewellery'), ('bottle', 'Bottle'), ('wallet', 'Wallet'), ('bags', 'Bags'), ('documents', 'Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=20),
        ),
    ]
